# Generated by Django 4.0.2 on 2022-03-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Toolname', models.CharField(max_length=50)),
                ('command', models.CharField(max_length=100)),
            ],
        ),
    ]
