# Generated by Django 4.0.2 on 2022-03-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnslookup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dns',
            new_name='Tools',
        ),
    ]
