# Generated by Django 4.0.2 on 2022-03-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnslookup', '0002_rename_dns_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='Toolname',
            field=models.CharField(choices=[('Dns', 'Dns'), ('Nmap', 'Nmap'), ('ping', 'ping'), ('Hping', 'Hping')], max_length=50),
        ),
    ]
