# Generated by Django 4.0.2 on 2022-03-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnslookup', '0003_alter_tools_toolname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=50)),
                ('query', models.CharField(max_length=35)),
            ],
        ),
    ]
